# -*- coding: utf-8 -*-
"""Bitcoin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z9M-gXdR7i-BZxXvx4pjQMgl_VS4e-Ec
"""

import requests

url = "https://yfapi.net/v6/finance/quote?region=US&lang=en&symbols=BTC-USD%3DX"

querystring = {"symbols":"AAPL,BTC-USD,EURUSD=X"}

headers = {
    'x-api-key': "a3HvvyAQfV55poUqvpUF7KrS32phDfqa8soGgrQ8"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)